version: '3.7'
services:
  backend:
    build:
      context: spring
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: react
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - "80:80"
    container_name: frontend
    restart: always
    depends_on:
      - backend
